[Settings]

[build]
  environment = { PANTHEON_ENV = "live" }
  functions = "./functions"

# dev environment settings
[context.dev]
  environment = { PANTHEON_ENV = "dev" }

# test environment settings
[context.test]
  environment = { PANTHEON_ENV = "test" }

# master environment settings
[context.production]
  environment = { PANTHEON_ENV = "live" }